<?php

namespace Database\Seeders;

use App\Models\Product;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        Product::truncate();

        $products = [

            /* ══════════════════════════════════════
               CATÉGORIE : BURGERS
            ══════════════════════════════════════ */
            [
                'name' => "Champion's Smash",
                'category' => 'burgers',
                'subcategory' => 'smash',
                'description' => 'Triple steak smashé, triple cheddar, bacon croustillant, sauce secrète maison, cornichons, oignon caramélisé',
                'ingredients' => 'Bœuf français 100%, cheddar affiné, bacon fumé, sauce secrète (mayo, ketchup, moutarde, épices), cornichons, oignon caramélisé, brioche toastée',
                'price' => 18.90,
                'badge' => 'Best-seller',
                'badge_color' => 'pink',
                'image_url' => 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=600&q=80',
                'is_halal' => false,
                'is_vegetarian' => false,
                'is_featured' => true,
                'allergens' => ['gluten', 'lait', 'œufs', 'moutarde'],
                'sort_order' => 1,
            ],
            [
                'name' => 'Classic Smash',
                'category' => 'burgers',
                'subcategory' => 'smash',
                'description' => 'Bœuf français smashé, cheddar fondu, salade, tomate, oignon, sauce maison',
                'ingredients' => 'Bœuf français 100%, cheddar, salade iceberg, tomate, oignon rouge, sauce maison, brioche toastée',
                'price' => 12.90,
                'badge' => null,
                'badge_color' => 'pink',
                'image_url' => 'https://images.unsplash.com/photo-1553979459-d2229ba7433b?w=600&q=80',
                'is_halal' => false,
                'is_vegetarian' => false,
                'is_featured' => false,
                'allergens' => ['gluten', 'lait', 'œufs', 'moutarde'],
                'sort_order' => 2,
            ],
            [
                'name' => 'Halal Smash',
                'category' => 'burgers',
                'subcategory' => 'halal',
                'description' => 'Bœuf Halal certifié, cheddar fondu, cornichons, sauce barbecue maison',
                'ingredients' => 'Bœuf Halal certifié, cheddar, cornichons, sauce barbecue, oignon, brioche toastée',
                'price' => 13.90,
                'badge' => 'Halal',
                'badge_color' => 'green',
                'image_url' => 'https://images.unsplash.com/photo-1594212699903-ec8a3eca50f5?w=600&q=80',
                'is_halal' => true,
                'is_vegetarian' => false,
                'is_featured' => true,
                'allergens' => ['gluten', 'lait', 'moutarde'],
                'sort_order' => 3,
            ],
            [
                'name' => 'Veggie Smash',
                'category' => 'burgers',
                'subcategory' => 'veggie',
                'description' => 'Galette végétale, cheddar vegan, avocat, roquette, sauce citron',
                'ingredients' => 'Galette végétale (pois chiches, betterave), cheddar vegan, avocat, roquette, tomate, sauce citron-herbes, brioche végane',
                'price' => 12.90,
                'badge' => 'Végétarien',
                'badge_color' => 'green',
                'image_url' => 'https://images.unsplash.com/photo-1607013251379-e6eecfffe234?w=600&q=80',
                'is_halal' => true,
                'is_vegetarian' => true,
                'is_vegan' => false,
                'is_featured' => false,
                'allergens' => ['gluten', 'céleri'],
                'sort_order' => 4,
            ],
            [
                'name' => 'Double Smash',
                'category' => 'burgers',
                'subcategory' => 'smash',
                'description' => '2 steaks smashés, double cheddar, sauce spéciale, cornichons, oignon',
                'ingredients' => 'Bœuf français 100% x2, double cheddar, sauce spéciale maison, cornichons, oignon, brioche toastée',
                'price' => 15.90,
                'badge' => null,
                'badge_color' => 'pink',
                'image_url' => 'https://images.unsplash.com/photo-1561758033-d89a9ad46330?w=600&q=80',
                'is_halal' => false,
                'is_vegetarian' => false,
                'is_featured' => false,
                'allergens' => ['gluten', 'lait', 'œufs', 'moutarde'],
                'sort_order' => 5,
            ],
            [
                'name' => 'Kids Burger',
                'category' => 'burgers',
                'subcategory' => 'kids',
                'description' => 'Mini burger, frites maison, boisson au choix — pour les petits aventuriers',
                'ingredients' => 'Mini steak bœuf, cheddar, ketchup, brioche mini, frites maison',
                'price' => 8.90,
                'badge' => 'Menu Enfant',
                'badge_color' => 'dark',
                'image_url' => 'https://images.unsplash.com/photo-1550547660-d9450f859349?w=600&q=80',
                'is_halal' => false,
                'is_vegetarian' => false,
                'is_featured' => false,
                'allergens' => ['gluten', 'lait'],
                'sort_order' => 6,
            ],

            /* ══════════════════════════════════════
               CATÉGORIE : BAGELS
            ══════════════════════════════════════ */
            [
                'name' => 'Egg & Bacon Bagel',
                'category' => 'bagels',
                'subcategory' => 'chaud',
                'description' => 'Œuf brouillé, bacon croustillant, cheddar fondu, sauce hollandaise',
                'ingredients' => 'Bagel nature, œuf brouillé, bacon fumé, cheddar, sauce hollandaise',
                'price' => 9.90,
                'badge' => 'Breakfast',
                'badge_color' => 'pink',
                'image_url' => 'https://images.unsplash.com/photo-1509722747041-616f39b57569?w=600&q=80',
                'is_halal' => false,
                'is_vegetarian' => false,
                'is_featured' => true,
                'allergens' => ['gluten', 'lait', 'œufs'],
                'sort_order' => 10,
            ],
            [
                'name' => 'Lost Bagel',
                'category' => 'bagels',
                'subcategory' => 'froid',
                'description' => 'Saumon fumé, cream cheese, câpres, oignon rouge, aneth frais',
                'ingredients' => 'Bagel sésame, saumon fumé Atlantique, cream cheese, câpres, oignon rouge, aneth, citron',
                'price' => 11.90,
                'badge' => 'Signature',
                'badge_color' => 'pink',
                'image_url' => 'https://images.unsplash.com/photo-1565299507177-b0ac66763828?w=600&q=80',
                'is_halal' => false,
                'is_vegetarian' => false,
                'is_featured' => true,
                'allergens' => ['gluten', 'lait', 'poisson', 'sésame'],
                'sort_order' => 11,
            ],
            [
                'name' => 'Chicken Avocado',
                'category' => 'bagels',
                'subcategory' => 'chaud',
                'description' => 'Poulet grillé, avocat, tomate, roquette, mayonnaise citron',
                'ingredients' => 'Bagel complet, poulet grillé, avocat, tomate, roquette, mayo citron-herbes',
                'price' => 10.90,
                'badge' => null,
                'badge_color' => 'pink',
                'image_url' => 'https://images.unsplash.com/photo-1550583724-b2692b85b150?w=600&q=80',
                'is_halal' => true,
                'is_vegetarian' => false,
                'is_featured' => false,
                'allergens' => ['gluten', 'œufs', 'moutarde'],
                'sort_order' => 12,
            ],
            [
                'name' => 'Veggie Bagel',
                'category' => 'bagels',
                'subcategory' => 'veggie',
                'description' => 'Houmous maison, légumes grillés, roquette, tomates séchées',
                'ingredients' => 'Bagel complet, houmous maison, courgette grillée, poivron, roquette, tomates séchées, huile d\'olive',
                'price' => 9.50,
                'badge' => 'Végétarien',
                'badge_color' => 'green',
                'image_url' => 'https://images.unsplash.com/photo-1484723091739-30a097e8f929?w=600&q=80',
                'is_halal' => true,
                'is_vegetarian' => true,
                'is_vegan' => true,
                'is_featured' => false,
                'allergens' => ['gluten', 'sésame', 'céleri'],
                'sort_order' => 13,
            ],
            [
                'name' => 'Build Your Own Bagel',
                'category' => 'bagels',
                'subcategory' => 'compose',
                'description' => 'Composez votre bagel parmi 12 ingrédients frais au choix',
                'ingredients' => 'Base bagel au choix + 3 ingrédients parmi : saumon, poulet, thon, œuf, cream cheese, avocat, tomate, concombre, roquette, câpres, oignon, cheddar',
                'price' => 8.50,
                'badge' => 'Personnalisé',
                'badge_color' => 'dark',
                'image_url' => 'https://images.unsplash.com/photo-1528735602780-2552fd46c7af?w=600&q=80',
                'is_halal' => false,
                'is_vegetarian' => false,
                'is_featured' => false,
                'allergens' => ['gluten'],
                'sort_order' => 14,
            ],

            /* ══════════════════════════════════════
               CATÉGORIE : CHEESECAKE
            ══════════════════════════════════════ */
            [
                'name' => 'New-Yorkais Classique',
                'category' => 'cheesecake',
                'subcategory' => 'classique',
                'description' => 'Recette traditionnelle du chef Jonathan Jablonski, base biscuitée croustillante, texture crémeuse sans gélatine',
                'ingredients' => 'Philadelphia, œufs, sucre, crème fraîche, vanille de Madagascar, base biscuits Graham',
                'price' => 6.90,
                'badge' => 'Signature',
                'badge_color' => 'pink',
                'image_url' => 'https://images.unsplash.com/photo-1565958011703-44f9829ba187?w=600&q=80',
                'is_halal' => true,
                'is_vegetarian' => true,
                'is_featured' => true,
                'allergens' => ['gluten', 'lait', 'œufs'],
                'sort_order' => 20,
            ],
            [
                'name' => 'Framboise – Chocolat Blanc',
                'category' => 'cheesecake',
                'subcategory' => 'fruité',
                'description' => 'Coulis de framboise fraîche, ganache chocolat blanc, base biscuitée',
                'ingredients' => 'Philadelphia, framboises fraîches, chocolat blanc Valrhona, crème, œufs, base biscuits',
                'price' => 7.50,
                'badge' => null,
                'badge_color' => 'pink',
                'image_url' => 'https://images.unsplash.com/photo-1533134242443-d4fd215305ad?w=600&q=80',
                'is_halal' => true,
                'is_vegetarian' => true,
                'is_featured' => false,
                'allergens' => ['gluten', 'lait', 'œufs'],
                'sort_order' => 21,
            ],
            [
                'name' => 'Oreo',
                'category' => 'cheesecake',
                'subcategory' => 'gourmand',
                'description' => 'Biscuits Oreo croustillants, crème onctueuse, topping Oreo concassé',
                'ingredients' => 'Philadelphia, biscuits Oreo, crème, œufs, sucre, vanille',
                'price' => 7.50,
                'badge' => null,
                'badge_color' => 'pink',
                'image_url' => 'https://images.unsplash.com/photo-1488477181946-6428a0291777?w=600&q=80',
                'is_halal' => true,
                'is_vegetarian' => true,
                'is_featured' => false,
                'allergens' => ['gluten', 'lait', 'œufs', 'soja'],
                'sort_order' => 22,
            ],
            [
                'name' => 'Kinder Bueno',
                'category' => 'cheesecake',
                'subcategory' => 'gourmand',
                'description' => 'Chocolat noisette, wafer croustillant, onctuosité maximale',
                'ingredients' => 'Philadelphia, Kinder Bueno, noisettes, chocolat au lait, crème, œufs',
                'price' => 7.50,
                'badge' => 'Coup de cœur',
                'badge_color' => 'dark',
                'image_url' => 'https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?w=600&q=80',
                'is_halal' => true,
                'is_vegetarian' => true,
                'is_featured' => true,
                'allergens' => ['gluten', 'lait', 'œufs', 'noisettes', 'soja'],
                'sort_order' => 23,
            ],
            [
                'name' => 'Spéculoos',
                'category' => 'cheesecake',
                'subcategory' => 'classique',
                'description' => 'Base spéculoos, caramel beurre salé, épices douces de Noël',
                'ingredients' => 'Philadelphia, spéculoos, caramel beurre salé, cannelle, gingembre, crème, œufs',
                'price' => 7.50,
                'badge' => null,
                'badge_color' => 'pink',
                'image_url' => 'https://images.unsplash.com/photo-1464305795204-6f5bbfc7fb81?w=600&q=80',
                'is_halal' => true,
                'is_vegetarian' => true,
                'is_featured' => false,
                'allergens' => ['gluten', 'lait', 'œufs', 'soja'],
                'sort_order' => 24,
            ],
            [
                'name' => 'Coffret 4 Parts',
                'category' => 'cheesecake',
                'subcategory' => 'emporter',
                'description' => '4 parts assorties à emporter dans un coffret cadeau — idéal pour la famille',
                'ingredients' => 'Sélection de 4 cheesecakes au choix parmi notre carte',
                'price' => 24.00,
                'badge' => 'À emporter',
                'badge_color' => 'dark',
                'image_url' => 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=600&q=80',
                'is_halal' => true,
                'is_vegetarian' => true,
                'is_featured' => false,
                'allergens' => ['gluten', 'lait', 'œufs'],
                'sort_order' => 25,
            ],

            /* ══════════════════════════════════════
               CATÉGORIE : BOWLS
            ══════════════════════════════════════ */
            [
                'name' => 'Super Bowl Quinoa',
                'category' => 'bowls',
                'subcategory' => 'vegan',
                'description' => 'Quinoa, avocat, edamame, carottes râpées, graines de courge, sauce tahini',
                'ingredients' => 'Quinoa bio, avocat, edamame, carottes, graines de courge, coriandre, sauce tahini-citron',
                'price' => 13.50,
                'badge' => 'Vegan',
                'badge_color' => 'green',
                'image_url' => 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=600&q=80',
                'is_halal' => true,
                'is_vegetarian' => true,
                'is_vegan' => true,
                'is_featured' => true,
                'allergens' => ['sésame', 'céleri'],
                'sort_order' => 30,
            ],
            [
                'name' => 'Chicken Power Bowl',
                'category' => 'bowls',
                'subcategory' => 'proteine',
                'description' => 'Poulet grillé, riz brun, légumes rôtis de saison, sauce yaourt-citron',
                'ingredients' => 'Poulet grillé, riz brun, courgette, poivron, carotte rôtis, sauce yaourt-citron-herbes',
                'price' => 14.50,
                'badge' => null,
                'badge_color' => 'pink',
                'image_url' => 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=600&q=80',
                'is_halal' => true,
                'is_vegetarian' => false,
                'is_featured' => false,
                'allergens' => ['lait'],
                'sort_order' => 31,
            ],
            [
                'name' => 'Salade César',
                'category' => 'bowls',
                'subcategory' => 'salade',
                'description' => 'Poulet croustillant, parmesan, croûtons maison, sauce César',
                'ingredients' => 'Laitue romaine, poulet croustillant, parmesan, croûtons maison, sauce César (anchois, ail, citron)',
                'price' => 12.90,
                'badge' => null,
                'badge_color' => 'pink',
                'image_url' => 'https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?w=600&q=80',
                'is_halal' => false,
                'is_vegetarian' => false,
                'is_featured' => false,
                'allergens' => ['gluten', 'lait', 'œufs', 'poisson', 'moutarde'],
                'sort_order' => 32,
            ],
            [
                'name' => 'Salade Saumon',
                'category' => 'bowls',
                'subcategory' => 'salade',
                'description' => 'Saumon fumé, avocat, concombre, radis, vinaigrette agrumes',
                'ingredients' => 'Mesclun, saumon fumé Atlantique, avocat, concombre, radis, vinaigrette orange-citron',
                'price' => 13.90,
                'badge' => null,
                'badge_color' => 'pink',
                'image_url' => 'https://images.unsplash.com/photo-1490645935967-10de6ba17061?w=600&q=80',
                'is_halal' => false,
                'is_vegetarian' => false,
                'is_featured' => false,
                'allergens' => ['poisson'],
                'sort_order' => 33,
            ],
            [
                'name' => 'Veggie Bowl',
                'category' => 'bowls',
                'subcategory' => 'veggie',
                'description' => 'Pois chiches rôtis, betterave, épinards, grenade, houmous maison',
                'ingredients' => 'Pois chiches rôtis, betterave, épinards baby, grenade, houmous maison, graines de tournesol',
                'price' => 12.50,
                'badge' => 'Végétarien',
                'badge_color' => 'green',
                'image_url' => 'https://images.unsplash.com/photo-1498837167922-ddd27525d352?w=600&q=80',
                'is_halal' => true,
                'is_vegetarian' => true,
                'is_vegan' => true,
                'is_featured' => false,
                'allergens' => ['sésame', 'céleri'],
                'sort_order' => 34,
            ],
            [
                'name' => 'Smoothie Bowl',
                'category' => 'bowls',
                'subcategory' => 'breakfast',
                'description' => 'Fruits frais mixés, granola croustillant, graines de chia, miel',
                'ingredients' => 'Banane, mangue, fraises, granola maison, graines de chia, miel, noix de coco râpée',
                'price' => 8.90,
                'badge' => 'Breakfast',
                'badge_color' => 'pink',
                'image_url' => 'https://images.unsplash.com/photo-1494390248081-4e521a5940db?w=600&q=80',
                'is_halal' => true,
                'is_vegetarian' => true,
                'is_vegan' => false,
                'is_featured' => false,
                'allergens' => ['gluten', 'noix'],
                'sort_order' => 35,
            ],
        ];

        foreach ($products as $data) {
            $data['slug'] = Str::slug($data['name']);
            Product::create($data);
        }

        $this->command->info('✅ '.count($products).' produits insérés.');
    }
}
