<?php

namespace Database\Seeders;

use App\Models\Product;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        Product::truncate();

        $products = [

            /* ══════════════════════════════════════
               CATÉGORIE : SMASH BURGERS
            ══════════════════════════════════════ */
            [
                'name' => 'Yankee',
                'category' => 'burgers',
                'subcategory' => 'smash',
                'description' => 'Le classique Factory & Co. Simple, efficace, smashé à la perfection.',
                'ingredients' => 'Steak smashé, cheddar, salade, tomate, oignon, sauce maison, brioche toastée',
                'price' => 6.80,
                'badge' => 'Regular 10,30€ · Big 13,80€',
                'badge_color' => 'pink',
                'image_url' => 'menu/SALÉ/BURGER/Smash Burgers/Yankee/Yankee Big/DSC03626.jpg',
                'is_halal' => true,
                'is_vegetarian' => false,
                'is_featured' => false,
                'allergens' => ['gluten', 'lait', 'œufs', 'moutarde'],
                'sort_order' => 1,
            ],
            [
                'name' => 'Cheeseburger',
                'category' => 'burgers',
                'subcategory' => 'smash',
                'description' => 'Bœuf de race, cheddar, tomate, oignon rouge, pickles, salade ciselée & sauce 1989 (notre sauce burger secrète)',
                'ingredients' => 'Steak smashé, double cheddar, cornichons, oignon, sauce secrète, brioche toastée',
                'price' => 8.80,
                'badge' => 'Regular 12,30€ · Big 15,80€',
                'badge_color' => 'pink',
                'image_url' => 'menu/SALÉ/BURGER/Smash Burgers/Cheeseburger/Cheeseburger Regular/DSC03883.jpg',
                'is_halal' => true,
                'is_vegetarian' => false,
                'is_featured' => true,
                'allergens' => ['gluten', 'lait', 'œufs', 'moutarde'],
                'sort_order' => 2,
            ],
            [
                'name' => 'Spicy Smash',
                'category' => 'burgers',
                'subcategory' => 'smash',
                'description' => 'Piment, jalapeños, sauce spicy maison. Pour les amateurs de sensations fortes.',
                'ingredients' => 'Steak smashé, cheddar, jalapeños, piment, sauce spicy maison, brioche toastée',
                'price' => 9.80,
                'badge' => 'Regular 13,30€ · Big 16,80€',
                'badge_color' => 'pink',
                'image_url' => 'menu/SALÉ/BURGER/Smash Burgers/Spicy Smash/Spicy Smash Regular/DSC03847.jpg',
                'is_halal' => true,
                'is_vegetarian' => false,
                'is_featured' => false,
                'allergens' => ['gluten', 'lait', 'œufs', 'moutarde'],
                'sort_order' => 3,
            ],
            [
                'name' => 'Golden',
                'category' => 'burgers',
                'subcategory' => 'smash',
                'description' => 'Bacon croustillant, cheddar affiné, sauce premium. Le burger signature.',
                'ingredients' => 'Steak smashé, bacon, cheddar affiné, salade, tomate, sauce premium, brioche toastée',
                'price' => 11.80,
                'badge' => 'Regular 15,30€ · Big 18,80€',
                'badge_color' => 'pink',
                'image_url' => 'menu/SALÉ/BURGER/Smash Burgers/Golden/Golden Regular/DSC03736.jpg',
                'is_halal' => true,
                'is_vegetarian' => false,
                'is_featured' => true,
                'allergens' => ['gluten', 'lait', 'œufs', 'moutarde'],
                'sort_order' => 4,
            ],
            [
                'name' => 'Southwestern',
                'category' => 'burgers',
                'subcategory' => 'smash',
                'description' => 'Guacamole, oignon croustillant, sauce southwestern. L\'Amérique du Sud dans un burger.',
                'ingredients' => 'Steak smashé, guacamole, oignon croustillant, cheddar, sauce southwestern, brioche toastée',
                'price' => 11.80,
                'badge' => 'Regular 15,30€ · Big 18,80€',
                'badge_color' => 'pink',
                'image_url' => 'menu/SALÉ/BURGER/Smash Burgers/Southwestern/Southwestern Big/DSC03659.jpg',
                'is_halal' => true,
                'is_vegetarian' => false,
                'is_featured' => false,
                'allergens' => ['gluten', 'lait', 'œufs', 'moutarde'],
                'sort_order' => 5,
            ],
            [
                'name' => 'Big Monster Truck',
                'category' => 'burgers',
                'subcategory' => 'smash',
                'description' => 'Le monstre. Triple steak, triple cheddar, bacon, sauce spéciale. Pour les gros appétits.',
                'ingredients' => 'Triple steak smashé, triple cheddar, bacon, cornichons, oignon, sauce spéciale, brioche toastée',
                'price' => 16.90,
                'badge' => 'XXL',
                'badge_color' => 'dark',
                'image_url' => 'menu/SALÉ/BURGER/Smash Burgers/Monster/DSC03550.jpg',
                'is_halal' => true,
                'is_vegetarian' => false,
                'is_featured' => true,
                'allergens' => ['gluten', 'lait', 'œufs', 'moutarde'],
                'sort_order' => 6,
            ],

            /* ══════════════════════════════════════
               CATÉGORIE : CHICKEN BURGERS
            ══════════════════════════════════════ */
            [
                'name' => 'Creamy Spicy Chicken',
                'category' => 'burgers',
                'subcategory' => 'chicken',
                'description' => 'Poulet croustillant, sauce crémeuse épicée, salade, tomate.',
                'ingredients' => 'Poulet pané croustillant, sauce crémeuse épicée, salade, tomate, brioche toastée',
                'price' => 9.80,
                'badge' => null,
                'badge_color' => 'pink',
                'image_url' => 'menu/SALÉ/BURGER/Chicken Burgers/Creamy Spicy Chicken.JPG',
                'is_halal' => true,
                'is_vegetarian' => false,
                'is_featured' => false,
                'allergens' => ['gluten', 'lait', 'œufs'],
                'sort_order' => 7,
            ],
            [
                'name' => 'Devil & Sweet Chicken',
                'category' => 'burgers',
                'subcategory' => 'chicken',
                'description' => 'Poulet croustillant, sauce sweet chili, coleslaw maison.',
                'ingredients' => 'Poulet pané croustillant, sauce sweet chili, coleslaw, brioche toastée',
                'price' => 9.80,
                'badge' => null,
                'badge_color' => 'pink',
                'image_url' => 'menu/SALÉ/BURGER/Factory x Plateforme 016.JPG',
                'is_halal' => true,
                'is_vegetarian' => false,
                'is_featured' => false,
                'allergens' => ['gluten', 'lait', 'œufs'],
                'sort_order' => 8,
            ],
            [
                'name' => 'Smoky Chicken',
                'category' => 'burgers',
                'subcategory' => 'chicken',
                'description' => 'Poulet croustillant, sauce smoky BBQ, oignon croustillant, cheddar.',
                'ingredients' => 'Poulet pané croustillant, sauce smoky BBQ, oignon croustillant, cheddar, brioche toastée',
                'price' => 10.80,
                'badge' => null,
                'badge_color' => 'pink',
                'image_url' => 'menu/SALÉ/BURGER/Chicken Burgers/Smoky Chicken.JPG',
                'is_halal' => true,
                'is_vegetarian' => false,
                'is_featured' => false,
                'allergens' => ['gluten', 'lait', 'œufs'],
                'sort_order' => 9,
            ],

            /* ══════════════════════════════════════
               CATÉGORIE : BAGELS
            ══════════════════════════════════════ */
            [
                'name' => 'Bagel Cream Cheese',
                'category' => 'bagels',
                'subcategory' => 'classique',
                'description' => 'Bagel toasté garni de cream cheese Philadelphia',
                'ingredients' => 'Bagel artisanal (36h de fermentation), cream cheese',
                'price' => 3.50,
                'badge' => null,
                'badge_color' => 'pink',
                'image_url' => 'menu/SALÉ/BAGELS/DSC00828.jpg',
                'is_halal' => true,
                'is_vegetarian' => true,
                'is_featured' => false,
                'allergens' => ['gluten', 'lait'],
                'sort_order' => 10,
            ],
            [
                'name' => 'B.L.T.',
                'category' => 'bagels',
                'subcategory' => 'chaud',
                'description' => 'Crispy bacon, tomate, salade ciselée & mayonnaise',
                'ingredients' => 'Bagel artisanal, crispy bacon, tomate, salade ciselée, mayonnaise',
                'price' => 8.90,
                'badge' => null,
                'badge_color' => 'pink',
                'image_url' => 'menu/SALÉ/BAGELS/Bagel BLT Seul 1.jpg',
                'is_halal' => false,
                'is_vegetarian' => false,
                'is_featured' => false,
                'allergens' => ['gluten', 'lait', 'œufs'],
                'sort_order' => 11,
            ],
            [
                'name' => 'New Yorker',
                'category' => 'bagels',
                'subcategory' => 'froid',
                'description' => 'Saumon fumé norvégien, cream cheese, oignon rouge & salade ciselée',
                'ingredients' => 'Bagel artisanal, saumon fumé norvégien, cream cheese, oignon rouge, salade ciselée',
                'price' => 9.90,
                'badge' => 'Signature',
                'badge_color' => 'pink',
                'image_url' => 'menu/SALÉ/BAGELS/Bagel New Yorker Seul Bis.jpg',
                'is_halal' => false,
                'is_vegetarian' => false,
                'is_featured' => true,
                'allergens' => ['gluten', 'lait', 'poisson'],
                'sort_order' => 12,
            ],
            [
                'name' => 'Bacon Lover',
                'category' => 'bagels',
                'subcategory' => 'chaud',
                'description' => 'Crispy bacon, cream cheese, cheddar, oignon rouge, tomate & avocat',
                'ingredients' => 'Bagel artisanal, crispy bacon, cream cheese, cheddar, oignon rouge, tomate, avocat',
                'price' => 10.90,
                'badge' => 'Breakfast',
                'badge_color' => 'pink',
                'image_url' => 'menu/SALÉ/BAGELS/Bagel Bacon Lover Seul.jpg',
                'is_halal' => false,
                'is_vegetarian' => false,
                'is_featured' => true,
                'allergens' => ['gluten', 'lait', 'œufs'],
                'sort_order' => 13,
            ],

            /* ══════════════════════════════════════
               CATÉGORIE : SUPER BOWLS
            ══════════════════════════════════════ */
            [
                'name' => 'César',
                'category' => 'bowls',
                'subcategory' => 'salade',
                'description' => 'Salade du moment, poulet grillé ou crunchy, Grana Padano, croûtons, tomates cerises, oignon rouge, ciboulette & sauce Cæsar',
                'ingredients' => 'Salade, poulet, Grana Padano, croûtons, tomates cerises, oignon rouge, ciboulette, sauce Cæsar',
                'price' => 12.90,
                'badge' => null,
                'badge_color' => 'pink',
                'image_url' => 'menu/SALÉ/BOWLS/DSC00510.jpg',
                'is_halal' => false,
                'is_vegetarian' => false,
                'is_featured' => false,
                'allergens' => ['gluten', 'lait', 'œufs', 'poisson', 'moutarde'],
                'sort_order' => 20,
            ],
            [
                'name' => 'US Marshall',
                'category' => 'bowls',
                'subcategory' => 'proteine',
                'description' => 'Salade du moment, bœuf de race smashé et grillé, guacamole maison, tomates cerises, feta, oignons frits, coriandre & sauce balsamique',
                'ingredients' => 'Salade, bœuf smashé, guacamole, tomates cerises, feta, oignons frits, coriandre, sauce balsamique',
                'price' => 13.90,
                'badge' => null,
                'badge_color' => 'pink',
                'image_url' => 'menu/SALÉ/BOWLS/US Marshall.jpg',
                'is_halal' => true,
                'is_vegetarian' => false,
                'is_featured' => false,
                'allergens' => ['lait'],
                'sort_order' => 21,
            ],
            [
                'name' => 'Cancoon',
                'category' => 'bowls',
                'subcategory' => 'proteine',
                'description' => 'Salade du moment, poulet grillé ou crunchy, feta, tomates cerises, crispy bacon, avocat, oignons frits, olives noires, cacahuètes, coriandre, pickles & sauce basilic',
                'ingredients' => 'Salade, poulet, feta, tomates cerises, bacon, avocat, oignons frits, olives, cacahuètes, coriandre, pickles, sauce basilic',
                'price' => 14.90,
                'badge' => 'Coup de cœur',
                'badge_color' => 'dark',
                'image_url' => 'menu/SALÉ/BOWLS/Cancoon 1.jpg',
                'is_halal' => true,
                'is_vegetarian' => false,
                'is_featured' => true,
                'allergens' => ['céleri'],
                'sort_order' => 22,
            ],

            /* ══════════════════════════════════════
               CATÉGORIE : CHEESECAKES
            ══════════════════════════════════════ */
            [
                'name' => 'New York Cheesecake',
                'category' => 'cheesecake',
                'subcategory' => 'classique',
                'description' => 'Cheesecake au zeste de citron et pointe de vanille, accompagné de son coulis',
                'ingredients' => 'Cream cheese, œufs, sucre, crème fraîche, vanille, base biscuits Graham',
                'price' => 5.50,
                'badge' => 'Signature',
                'badge_color' => 'pink',
                'image_url' => 'menu/SUCRÉ/CHEESECAKE/Cheesecake New York.JPG',
                'is_halal' => true,
                'is_vegetarian' => true,
                'is_featured' => true,
                'allergens' => ['gluten', 'lait', 'œufs'],
                'sort_order' => 30,
            ],
            [
                'name' => 'Spéculoos',
                'category' => 'cheesecake',
                'subcategory' => 'classique',
                'description' => '',
                'ingredients' => 'Cream cheese, spéculoos, caramel beurre salé, cannelle, crème, œufs',
                'price' => 6.50,
                'badge' => null,
                'badge_color' => 'pink',
                'image_url' => 'menu/SUCRÉ/CHEESECAKE/Cheesecake Speculoos.JPG',
                'is_halal' => true,
                'is_vegetarian' => true,
                'is_featured' => false,
                'allergens' => ['gluten', 'lait', 'œufs', 'soja'],
                'sort_order' => 31,
            ],
            [
                'name' => 'Oréo',
                'category' => 'cheesecake',
                'subcategory' => 'gourmand',
                'description' => '',
                'ingredients' => 'Cream cheese, biscuits Oréo, crème, œufs, sucre, vanille',
                'price' => 6.50,
                'badge' => null,
                'badge_color' => 'pink',
                'image_url' => 'menu/SUCRÉ/CHEESECAKE/Cheesecake Oreo 1.JPG',
                'is_halal' => true,
                'is_vegetarian' => true,
                'is_featured' => false,
                'allergens' => ['gluten', 'lait', 'œufs', 'soja'],
                'sort_order' => 32,
            ],
            [
                'name' => 'Kinder Bueno',
                'category' => 'cheesecake',
                'subcategory' => 'gourmand',
                'description' => '',
                'ingredients' => 'Cream cheese, Kinder Bueno, noisettes, chocolat au lait, crème, œufs',
                'price' => 6.50,
                'badge' => 'Coup de cœur',
                'badge_color' => 'dark',
                'image_url' => 'menu/SUCRÉ/CHEESECAKE/Cheesecake Kinder Bueno.JPG',
                'is_halal' => true,
                'is_vegetarian' => true,
                'is_featured' => true,
                'allergens' => ['gluten', 'lait', 'œufs', 'noisettes', 'soja'],
                'sort_order' => 33,
            ],
            [
                'name' => 'Nutella',
                'category' => 'cheesecake',
                'subcategory' => 'gourmand',
                'description' => '',
                'ingredients' => 'Cream cheese, Nutella, chocolat, noisettes, crème, œufs',
                'price' => 6.50,
                'badge' => null,
                'badge_color' => 'pink',
                'image_url' => 'menu/SUCRÉ/CHEESECAKE/Factory_Claye 17.JPG',
                'is_halal' => true,
                'is_vegetarian' => true,
                'is_featured' => false,
                'allergens' => ['gluten', 'lait', 'œufs', 'noisettes', 'soja'],
                'sort_order' => 34,
            ],
            [
                'name' => 'Framboise Chocolat Blanc',
                'category' => 'cheesecake',
                'subcategory' => 'fruité',
                'description' => '',
                'ingredients' => 'Cream cheese, framboises fraîches, chocolat blanc, crème, œufs',
                'price' => 6.50,
                'badge' => null,
                'badge_color' => 'pink',
                'image_url' => 'menu/SUCRÉ/CHEESECAKE/Cheesecake Framboises Chocolat Blanc.JPG',
                'is_halal' => true,
                'is_vegetarian' => true,
                'is_featured' => false,
                'allergens' => ['gluten', 'lait', 'œufs'],
                'sort_order' => 35,
            ],
            [
                'name' => 'Snickers',
                'category' => 'cheesecake',
                'subcategory' => 'gourmand',
                'description' => '',
                'ingredients' => 'Cream cheese, Snickers, caramel, cacahuètes, chocolat, crème, œufs',
                'price' => 6.50,
                'badge' => null,
                'badge_color' => 'pink',
                'image_url' => 'menu/SUCRÉ/CHEESECAKE/Cheesecake Snickers.JPG',
                'is_halal' => true,
                'is_vegetarian' => true,
                'is_featured' => false,
                'allergens' => ['gluten', 'lait', 'œufs', 'arachides', 'soja'],
                'sort_order' => 36,
            ],
        ];

        foreach ($products as $data) {
            $data['slug'] = Str::slug($data['name']);
            Product::create($data);
        }

        $this->command->info('✅ '.count($products).' produits insérés (carte officielle PDF).');
    }
}
